Updated composer config, added postgres & redis images

diff --git a/backend/php/Dockerfile b/backend/php/Dockerfile
--- a/backend/php/Dockerfile
+++ b/backend/php/Dockerfile
@@ -1,7 +1,6 @@
 FROM debian:buster-slim
 
-ARG BLU='\e[44m\n\n'
-ARG RES='\n\e[49m'
+LABEL org.opencontainers.image.authors="sv.rogulin@gmail.com"
 
 ARG PHP_VERSION=8.1.11
 ARG PHP_CFLAGS="-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
@@ -9,6 +8,8 @@ ARG PHP_CPPFLAGS=$PHP_CFLAGS
 ARG PHP_LDFLAGS="-Wl,-O1 -pie"
 ARG PHP_EXTENSION_IGBINARY_VERSION=3.2.9
 ARG PHP_EXTENSION_XDEBUG_VERSION=3.1.5
+ARG PHP_EXTENSION_XDEBUG_PORT=9003
+ARG PHP_EXTENSION_XDEBUG_LOG_LEVEL=7
 ARG PHP_EXTENSION_XHPROF_VERSION=2.3.7
 ARG PHP_EXTENSION_MEMCACHED_VERSION=3.2.0
 ARG PHP_EXTENSION_REDIS_VERSION=5.3.7
@@ -17,6 +18,7 @@ ARG PHP_EXTENSION_GRPC_VERSION=1.49.0
 ARG PHP_EXTENSION_PROTOBUF_VERSION=3.21.7
 ARG PHP_EXTENSION_YAML_VERSION=2.2.2
 ARG PHP_EXTENSION_SWOOLE_VERSION=4.8.12
+ARG PHP_EXTENSION_MAILPARSE_VERSION=3.1.4
 ARG PHP_EXTENSION_IMAGICK_BRANCH=3.7.0
 ARG PHP_EXTENSION_AMQP_BRANCH=v1.11.0
 ARG ORACLE_CLIENT_MAJOR_VERSION=21
@@ -24,42 +26,11 @@ ARG ORACLE_CLIENT_MINOR_VERSION=7
 ARG ORACLE_CLIENT_BRANCH=217000
 ARG ORACLE_CLIENT_VERSION="x64-21.7.0.0.0dbru"
 ARG ORACLE_NLS_LANG=American_America.CL8MSWIN1251
-ARG NODE_VERSION=18.11.0
 ARG MOZJPEG_VERSION=4.1.1
 ARG GIFSICLE_VERSION=1.93
 ARG MAILHOG_VERSION=1.0.1
 ARG MAILHOG_STORAGE="maildir"
 # ARG MAILHOG_STORAGE="memory"
-ARG PHP_DEPS=' \
-    ghostscript \
-    libaio1 \
-    libzip-dev \
-    libargon2-dev \
-    libcurl4-openssl-dev \
-    libedit-dev \
-    libc-client-dev \
-    libldb-dev \
-    libldap2-dev \
-    libsodium-dev \
-    libsqlite3-dev \
-    libxml2-dev \
-    libkrb5-dev \
-    libbz2-dev \
-    libffi-dev \
-    libgmp-dev \
-    libwebp-dev \
-    libpng-dev \
-    libonig-dev \
-    libreadline-dev \
-    libtidy-dev \
-    libmagickwand-dev \
-    libmemcached-dev \
-    libgs-dev \
-    libyaml-dev \
-    librabbitmq-dev \
-    libxslt-dev \
-    libpq-dev \
-'
 
 ENV PATH /usr/lib/oracle/instantclient_${ORACLE_CLIENT_MAJOR_VERSION}_${ORACLE_CLIENT_MINOR_VERSION}:${PATH}
 ENV ORACLE_HOME /usr/lib/oracle/instantclient_${ORACLE_CLIENT_MAJOR_VERSION}_${ORACLE_CLIENT_MINOR_VERSION}
@@ -72,14 +43,18 @@ ENV MH_API_BIND_ADDR 0.0.0.0:8025
 ENV MH_UI_BIND_ADDR 0.0.0.0:8025
 ENV MH_STORAGE ${MAILHOG_STORAGE}
 ENV MH_MAILDIR_PATH /var/mailhog
+ENV http_proxy=${SECURITY_HTTP_PROXY:-}
+ENV https_proxy=${SECURITY_HTTPS_PROXY:-}
 
 # INSTALLING PACKAGES...
 RUN set -eux; \
-    echo "${BLU}INSTALLING PACKAGES...${RES}"; \
+    echo "INSTALLING PACKAGES..."; \
     { echo 'Package: php*'; echo 'Pin: release *'; echo 'Pin-Priority: -1'; } > /etc/apt/preferences.d/no-debian-php; \
     apt-get update; \
     apt-get install --no-install-recommends --no-install-suggests -y \
 # UTILS...
+        locales \
+        tzdata \
         wget \
         ca-certificates \
         unzip \
@@ -101,12 +76,104 @@ RUN set -eux; \
         file \
         nasm \
 # PHP DEPENDENCIES...
-        ${PHP_DEPS}; \
-    apt-mark manual \
-        ${PHP_DEPS};
+        ghostscript \
+        libaio1 \
+        libzip-dev \
+        libargon2-dev \
+        libcurl4-openssl-dev \
+        libedit-dev \
+        libc-client-dev \
+        libldb-dev \
+        libldap2-dev \
+        libsodium-dev \
+        libsqlite3-dev \
+        libxml2-dev \
+        libkrb5-dev \
+        libbz2-dev \
+        libffi-dev \
+        libgmp-dev \
+        libwebp-dev \
+        libpng-dev \
+        libonig-dev \
+        libreadline-dev \
+        libtidy-dev \
+        libmagickwand-dev \
+        libmemcached-dev \
+        libgs-dev \
+        libyaml-dev \
+        librabbitmq-dev \
+        libxslt-dev \
+        libpq-dev; \
+# CONFIGURING TIMEZONE AND LOCALE...
+    echo "CONFIGURING TIMEZONE AND LOCALE..."; \
+    locale-gen ru_RU.UTF-8 en_US.UTF-8; \
+    touch /etc/tzdata-selection.txt; \
+    echo 'tzdata tzdata/Areas select Europe' >> /etc/tzdata-selection.txt; \
+    echo 'tzdata tzdata/Zones/Europe select Moscow' >> /etc/tzdata-selection.txt; \
+    debconf-set-selections /etc/tzdata-selection.txt; \
+    DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure tzdata; \
+# CONFIGURING MSMTP...
+    echo "CONFIGURING MSMTP..."; \
+    touch /var/log/msmtp.log; \
+    chown www-data:www-data /var/log/msmtp.log;
+
+## PACKAGES: MOZJPEG, GIFSICLE
 # DOWNLOADING SOURCES...
 RUN set -eux; \
-    echo "${BLU}DOWNLOADING SOURCES...${RES}"; \
+    echo "DOWNLOADING SOURCES..."; \
+    wget -O /tmp/mozjpeg-${MOZJPEG_VERSION}.tar.gz https://github.com/mozilla/mozjpeg/archive/v${MOZJPEG_VERSION}.tar.gz; \
+    wget -O /tmp/gifsicle-${GIFSICLE_VERSION}.tar.gz https://github.com/kohler/gifsicle/archive/v${GIFSICLE_VERSION}.tar.gz; \
+# UNPACKING SOURCES...
+    echo "UNPACKING SOURCES..."; \
+    tar -zxf /tmp/mozjpeg-${MOZJPEG_VERSION}.tar.gz -C /tmp; \
+    tar -zxf /tmp/gifsicle-${GIFSICLE_VERSION}.tar.gz -C /tmp; \
+# COMPILING MOJZPEG...
+    echo "COMPILING MOJZPEG..."; \
+    cd /tmp/mozjpeg-${MOZJPEG_VERSION}; \
+    mkdir build; \
+    cd build; \
+    cmake -G"Unix Makefiles" ../; \
+    make; \
+    make install; \
+    ln -s /opt/mozjpeg/bin/jpegtran /usr/bin/mozjpeg; \
+# SMOKE TEST
+    echo "CHECKING MOJZPEG..."; \
+    mozjpeg -version; \
+# COMPILING GIFSICLE...
+    echo "COMPILING GIFSICLE..."; \
+    cd /tmp/gifsicle-${GIFSICLE_VERSION}; \
+    autoreconf -i; \
+    ./configure \
+        --prefix=/usr/local \
+        --disable-gifview \
+        --disable-warnings; \
+    make; \
+    make install; \
+# SMOKE TEST
+    echo "CHECKING GIFSICLE..."; \
+    gifsicle --version; \
+# CLEANUP
+    echo "REMOVING PACKAGES..."; \
+    rm -rf /tmp/*;
+
+## PACKAGES: MAILHOG
+# DOWNLOADING SOURCES...
+RUN set -eux; \
+    echo "DOWNLOADING SOURCES..."; \
+    wget -O /tmp/mailhog https://github.com/mailhog/MailHog/releases/download/v${MAILHOG_VERSION}/MailHog_linux_amd64; \
+# INSTALLIGN MAILHOG...
+    echo "INSTALLING MAILHOG..."; \
+    addgroup --system --gid 1001 mailhog; \
+    adduser --system --disabled-login --ingroup mailhog --no-create-home --home /nonexistent --gecos "mailhog user" --shell /bin/false --uid 1001 mailhog; \
+    mkdir ${MH_MAILDIR_PATH}; \
+    chown mailhog:mailhog ${MH_MAILDIR_PATH}; \
+    mv /tmp/mailhog /usr/local/bin/mailhog; \
+    chmod +x /usr/local/bin/mailhog;
+
+## PACKAGE: PHP
+# DOWNLOADING SOURCES...
+RUN set -eux; \
+    echo "DOWNLOADING SOURCES..."; \
     wget -O /tmp/php-${PHP_VERSION}.tar.gz https://www.php.net/distributions/php-${PHP_VERSION}.tar.gz; \
     wget -O /tmp/instantclient-basic-linux.${ORACLE_CLIENT_VERSION}.zip https://download.oracle.com/otn_software/linux/instantclient/${ORACLE_CLIENT_BRANCH}/instantclient-basic-linux.${ORACLE_CLIENT_VERSION}.zip; \
     wget -O /tmp/instantclient-sqlplus-linux.${ORACLE_CLIENT_VERSION}.zip https://download.oracle.com/otn_software/linux/instantclient/${ORACLE_CLIENT_BRANCH}/instantclient-sqlplus-linux.${ORACLE_CLIENT_VERSION}.zip; \
@@ -114,14 +181,10 @@ RUN set -eux; \
     wget -O /tmp/instantclient-jdbc-linux.${ORACLE_CLIENT_VERSION}.zip https://download.oracle.com/otn_software/linux/instantclient/${ORACLE_CLIENT_BRANCH}/instantclient-jdbc-linux.${ORACLE_CLIENT_VERSION}.zip; \
     wget -O /tmp/instantclient-odbc-linux.${ORACLE_CLIENT_VERSION}.zip https://download.oracle.com/otn_software/linux/instantclient/${ORACLE_CLIENT_BRANCH}/instantclient-odbc-linux.${ORACLE_CLIENT_VERSION}.zip; \
     wget -O /tmp/composer-installer.php https://getcomposer.org/installer; \
-    wget -O /tmp/node-${NODE_VERSION}.tar.gz https://github.com/nodejs/node/archive/v${NODE_VERSION}.tar.gz; \
-    wget -O /tmp/mozjpeg-${MOZJPEG_VERSION}.tar.gz https://github.com/mozilla/mozjpeg/archive/v${MOZJPEG_VERSION}.tar.gz; \
-    wget -O /tmp/gifsicle-${GIFSICLE_VERSION}.tar.gz https://github.com/kohler/gifsicle/archive/v${GIFSICLE_VERSION}.tar.gz; \
-    wget -O /tmp/mailhog https://github.com/mailhog/MailHog/releases/download/v${MAILHOG_VERSION}/MailHog_linux_amd64; \
     git clone --branch ${PHP_EXTENSION_IMAGICK_BRANCH} --depth 1 https://github.com/Imagick/imagick /tmp/imagick; \
     git clone --branch ${PHP_EXTENSION_AMQP_BRANCH} --depth 1 https://github.com/php-amqp/php-amqp.git /tmp/amqp; \
 # UNPACKING SOURCES...
-    echo "${BLU}UNPACKING SOURCES...${RES}"; \
+    echo "UNPACKING SOURCES..."; \
     tar -zxf /tmp/php-${PHP_VERSION}.tar.gz -C /tmp; \
     mkdir -p /usr/lib/oracle; \
     unzip /tmp/instantclient-basic-linux.${ORACLE_CLIENT_VERSION}.zip -d /usr/lib/oracle; \
@@ -129,15 +192,10 @@ RUN set -eux; \
     unzip /tmp/instantclient-sdk-linux.${ORACLE_CLIENT_VERSION}.zip -d /usr/lib/oracle; \
     unzip /tmp/instantclient-jdbc-linux.${ORACLE_CLIENT_VERSION}.zip -d /usr/lib/oracle; \
     unzip /tmp/instantclient-odbc-linux.${ORACLE_CLIENT_VERSION}.zip -d /usr/lib/oracle; \
-    tar -zxf /tmp/node-${NODE_VERSION}.tar.gz -C /tmp; \
-    tar -zxf /tmp/mozjpeg-${MOZJPEG_VERSION}.tar.gz -C /tmp; \
-    tar -zxf /tmp/gifsicle-${GIFSICLE_VERSION}.tar.gz -C /tmp;
 # COMPILING PHP...
-RUN set -eux; \
-    echo "${BLU}COMPILING PHP...${RES}"; \
+    echo "COMPILING PHP..."; \
     ln -s /usr/lib/libc-client.a /usr/lib/x86_64-linux-gnu/libc-client.a; \
-    ln -s /usr/lib/libc-client.so /usr/lib/x86_64-linux-gnu/libc-client.so;
-RUN set -eux; \
+    ln -s /usr/lib/libc-client.so /usr/lib/x86_64-linux-gnu/libc-client.so; \
     cd /tmp/php-${PHP_VERSION}; \
     CFLAGS="${PHP_CFLAGS}" CPPFLAGS="${PHP_CPPFLAGS}" LDFLAGS="${PHP_LDFLAGS}" ./configure \
         --prefix=/usr \
@@ -201,10 +259,8 @@ RUN set -eux; \
     find -type f -name '*.a' -delete; \
     make install; \
     find /usr/local -type f -perm '/0111' -exec sh -euxc 'strip --strip-all "$@" || :' -- '{}' + ; \
-    make clean;
 # COMPILING PHP EXTENSIONS...
-RUN set -eux; \
-    echo "${BLU}COMPILING PHP EXTENSIONS...${RES}"; \
+    echo "COMPILING PHP EXTENSIONS..."; \
     mkdir -p /etc/php/conf.d/; \
     cd /tmp/php-${PHP_VERSION}/ext/oci8; \
     /usr/bin/phpize; \
@@ -250,6 +306,8 @@ RUN set -eux; \
     echo 'extension=redis' > /etc/php/conf.d/php-ext-redis.ini; \
     pecl install mongodb-${PHP_EXTENSION_MONGODB_VERSION}; \
     echo 'extension=mongodb' > /etc/php/conf.d/php-ext-mongodb.ini; \
+    pecl install mailparse-${PHP_EXTENSION_MAILPARSE_VERSION}; \
+    echo 'extension=mailparse' > /etc/php/conf.d/php-ext-mailparse.ini; \
     cd /tmp/imagick; \
     /usr/bin/phpize; \
     ./configure; \
@@ -293,8 +351,10 @@ RUN set -eux; \
     make -j$(nproc); \
     make install; \
     echo 'extension=swoole' > /etc/php/conf.d/php-ext-swoole.ini; \
+    echo 'extension=sodium' > /etc/php/conf.d/php-ext-sodium.ini; \
+    echo 'zend_extension=opcache' > /etc/php/conf.d/php-ext-opcache.ini; \
 # CONFIGURING PHP...
-    echo "${BLU}CONFIGURING PHP...${RES}"; \
+    echo "CONFIGURING PHP..."; \
     ln -s /usr/etc/php-fpm.d /etc/php/php-fpm.d; \
     { \
         echo "env[ORACLE_HOME] = ${ORACLE_HOME}"; \
@@ -308,9 +368,9 @@ RUN set -eux; \
         echo; \
         echo 'xdebug.mode=debug'; \
         echo 'xdebug.client_host=host.docker.internal'; \
-        echo 'xdebug.client_port=9003'; \
+        echo "xdebug.client_port=${PHP_EXTENSION_XDEBUG_PORT}"; \
         echo 'xdebug.log=/var/log/php/xdebug.log'; \
-        echo 'xdebug.log_level=7'; \
+        echo "xdebug.log_level=${PHP_EXTENSION_XDEBUG_LOG_LEVEL}"; \
         echo 'xdebug.output_dir=/var/log/php/cachegrind'; \
         echo 'xdebug.profiler_output_name=cachegrind.out.%s'; \
     } >> /etc/php/conf.d/php-ext-xdebug.ini; \
@@ -326,72 +386,24 @@ RUN set -eux; \
     mkdir -p /var/log/php/cachegrind; \
     chown www-data:www-data /var/log/php/cachegrind; \
 # SMOKE TEST
-    echo "${BLU}CHECKING PHP...${RES}"; \
+    echo "CHECKING PHP..."; \
     php --version; \
 # INSTALLING COMPOSER...
-    echo "${BLU}INSTALLING COMPOSER...${RES}"; \
+    echo "INSTALLING COMPOSER..."; \
     php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer; \
 # SMOKE TEST
-    echo "${BLU}CHECKING COMPOSER...${RES}"; \
-    composer --version;
-# COMPILING NODEJS...
-RUN set -eux; \
-    echo "${BLU}COMPILING NODEJS...${RES}"; \
-    addgroup --system --gid 1000 node; \
-    adduser --system --disabled-login --ingroup node --no-create-home --home /nonexistent --gecos "node user" --shell /bin/false --uid 1000 node; \
-    cd /tmp/node-${NODE_VERSION}; \
-    ./configure \
-        --prefix=/usr/local \
-        --verbose; \
-    make -j$(nproc); \
-    make install; \
-    ln -s /usr/local/bin/node /usr/local/bin/nodejs; \
-# CONFIGURING NODEJS...
-    echo "${BLU}CONFIGURING NODEJS...${RES}"; \
-    mkdir -p /var/log/node; \
-    chown www-data:www-data /var/log/node; \
-# SMOKE TEST
-    echo "${BLU}CHECKING NODEJS...${RES}"; \
-    node --version; \
-    npm --version; \
-    npx --version;
-# COMPILING MOJZPEG...
-RUN set -eux; \    
-    echo "${BLU}COMPILING MOJZPEG...${RES}"; \
-    cd /tmp/mozjpeg-${MOZJPEG_VERSION}; \
-    mkdir build; \
-    cd build; \
-    cmake -G"Unix Makefiles" ../; \
-    make; \
-    make install; \
-    ln -s /opt/mozjpeg/bin/jpegtran /usr/bin/mozjpeg; \
-# SMOKE TEST
-    echo "${BLU}CHECKING MOJZPEG...${RES}"; \
-    mozjpeg -version; \
-# COMPILING GIFSICLE...    
-    echo "${BLU}COMPILING GIFSICLE...${RES}"; \
-    cd /tmp/gifsicle-${GIFSICLE_VERSION}; \
-    autoreconf -i; \
-    ./configure \
-        --prefix=/usr/local \
-        --disable-gifview \
-        --disable-warnings; \
-    make; \
-    make install; \
-# SMOKE TEST
-    echo "${BLU}CHECKING GIFSICLE...${RES}"; \
-    gifsicle --version; \
-# INSTALLIGN MAILHOG...
-    echo "${BLU}INSTALLING MAILHOG...${RES}"; \
-    addgroup --system --gid 1001 mailhog; \
-    adduser --system --disabled-login --ingroup mailhog --no-create-home --home /nonexistent --gecos "mailhog user" --shell /bin/false --uid 1001 mailhog; \
-    mkdir ${MH_MAILDIR_PATH}; \
-    chown mailhog:mailhog ${MH_MAILDIR_PATH}; \
-    mv /tmp/mailhog /usr/local/bin/mailhog; \
-    chmod +x /usr/local/bin/mailhog;
+    echo "CHECKING COMPOSER..."; \
+    composer --version; \
 # CLEANUP
+    echo "REMOVING PACKAGES..."; \
+    pecl clear-cache; \
+    rm ~/.pearrc; \
+    rm -rf /usr/src/php; \
+    rm -rf /tmp/*;
+
+# SYSTEM CLEANUP...
 RUN set -eux; \
-    echo "${BLU}REMOVING PACKAGES...${RES}"; \
+    echo "SYSTEM CLEANUP..."; \
     apt-get remove --purge -y \
         git \
         g++ \
@@ -401,12 +413,9 @@ RUN set -eux; \
         autoconf \
         dpkg-dev \
         file \
-        nasm; \
-    find /usr/local -type f -executable -or -name \*.so -exec ldd '{}' ';' | awk '/=>/ { print $(NF-1) }' | sort -u | xargs -r dpkg-query --search | cut -d: -f1 | sort -u | xargs -r apt-mark manual; \
-    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
-    pecl clear-cache; \
-    npm cache clean --force; \
-    rm -rf /tmp/*;
+        nasm;
+    # find /usr/local -type f -executable -or -name \*.so -exec ldd '{}' ';' | awk '/=>/ { print $(NF-1) }' | sort -u | xargs -r dpkg-query --search | cut -d: -f1 | sort -u | xargs -r apt-mark manual; \
+    # apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
 
 COPY config/php/php.ini /etc/php/php.ini
 COPY config/php/php-fpm.conf /usr/etc/php-fpm.conf
@@ -414,28 +423,19 @@ COPY config/php/php-fpm.d/* /etc/php/php-fpm.d/
 COPY config/php/conf.d/* /etc/php/conf.d/
 COPY config/msmtprc /etc/msmtprc
 COPY config/supervisord/supervisord.conf /etc/supervisord.conf
-COPY config/supervisord/conf.d/* /etc/supervisor/conf.d/
 COPY scripts/start.sh /start.sh
 COPY scripts/prefix.sh /prefix.sh
 
-# CONFIGURING SUPERVISOR...
-RUN set -eux; \
-    echo "${BLU}CONFIGURING SUPERVISOR...${RES}"; \
-    mkdir -p /etc/supervisor/conf.d/; \
-# CONFIGURING MSMTP...
-    echo "${BLU}CONFIGURING MSMTP...${RES}"; \
-    touch /var/log/msmtp.log; \
-    chown www-data:www-data /var/log/msmtp.log; \
 # CONFIGURING STARTUP SCRIPTS...
-    echo "${BLU}CONFIGURING STARTUP SCRIPTS...${RES}"; \
+RUN set -eux; \
+    echo "CONFIGURING STARTUP SCRIPTS..."; \
     chmod 755 /start.sh; \
     chmod 755 /prefix.sh
 
-EXPOSE 3000 5000 8025 9002
+EXPOSE 8025 9003 9011
 VOLUME /var/mailhog
 VOLUME /var/www
 VOLUME /var/log/php
-VOLUME /var/log/node
 # VOLUME /var/log/profiler
 
 WORKDIR "/var/www"
